### PR TITLE
Enable Undertow on HTTP/2

### PR DESCRIPTION
**Pull request by ruhan1**
As subject.
To me, this seems the only thing we need to enable HTTP/2 on Undertow.

### CODE REVIEW

**Review by ligangty — APPROVED** [review]
LGTM. We need to test this later on indy. I remember new undertow version has caused some ftests failure in indy, not sure if it works with this update.

**Comment by ruhan1** [comment]
Ok. The cur undertow version supports http2 too. If this has problem, we can revert it.

**Comment by jdcasey** [comment]
This looks good, but we're also going to have to handle HTTP/2 on the generic proxy side.

**Review by jdcasey — APPROVED** [review]

**Comment by ruhan1** [comment]
@jdcasey what if we put off generic proxy http2? imo, because 1. most traffic are not through proxy. 2. for those through proxy, most are **https** requests; and the proxy simply connect the client to remote, so that there are little we can do wrt performance.

**Pull request merged**
